### ISSUE TITLE
Geolocation automatic switching not working

### ISSUE THREAD

**Issue by ghost** [gharveymn/nightswitch#1]
I can switch themes using the HUD commands but automatic switching is not working. Is there a way to debug? I'm using the latest Insiders release.

**Comment by gharveymn** [comment]
Thanks for the report. I think I renamed `nightswitch.geolocation` to `nightswitch.useGeoLocation` at some moment of madness and missed some of them, so I turned them all back to `nightswitch.geolocation`. Hopefully that helps.

If that didn't fix it, please feel free to clone the repo and download the modules specified in the readme. You can then open the folder in VSCode and just hit debug (after uninstalling the extension). I've left the log output in for now.

**Comment by ghost** [comment]
Hi Gene, I finally found some time to download the extension and manually install it. I'm now getting errors like "command 'extension.switchDay' not found" when I try to switch manually. 

oops, that was a reading comprehension problem 😳

I have opened the folder and started debugging. This is the output:
```
Debugging with legacy protocol because Node.js v7.10.0 was detected.
node --debug-brk=39476 --nolazy 
(node:7688) DeprecationWarning: node --debug is deprecated. Please use node --inspect instead.
Debugger listening on 127.0.0.1:39476
```
Where do I go from here?

**Comment by gharveymn** [comment]
Hey there, sorry that I missed some detail on installing for debugging, I hadn't actually tried migrating to a different computer before. 

So you'll want to clone just as before, but you'll need to drop the .vscode folder in the zip file attached into the project (it's just the build config that Yeoman generates) and then bring up the terminal to run the command `npm install`. After that, we just need `npm install suncalc`, `npm install geoip-lite`, and `npm install get-ip` and you should be set (you might need to restart VSCode if you did from the embedded terminal). 

After all that just open up the folder and hit the start debugging button, you should see output in the debug console.

[vscode.zip](https://github.com/gharveymn/nightswitch/files/1016995/vscode.zip)

**Comment by ghost** [comment]
It looks like the code is trying to use my lan IP and failing to look it up. I added this just before line 79 of extension.ts:
```
console.log('geoip: ' + geoip.lookup(ip) + ' ip: ' + ip);
```
```
geoip: null ip: 192.168.144.100
```

**Comment by ghost** [comment]
If I hardcode my public IP, then the extension works as expected.

My system is macOS Sierra 10.12.

Looking as the README for get-ip, it's supposed to get the internal IP.

**Comment by gharveymn** [comment]
Great detective work! I switched out the module from `get-ip` to `public-ip`, which hopefully works as advertised. Thanks for the help.
