### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by denbon05** [gharveymn/nightswitch#11]
- Issue Type: `Bug`
- Extension Name: `nightswitch`
- Extension Version: `1.3.0`
- OS Version: `Linux x64 5.8.0-59-generic`
- VS Code version: `1.58.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by gharveymn** [comment]
Did you forget to paste the data? Otherwise can I get some context?
