### ISSUE TITLE
Stops working when Linux comes out of suspension

### ISSUE THREAD

**Issue by vacore** [gharveymn/nightswitch#2]
I usually suspend my PC with VSCode left open, and after wakeup, I need to restart VSCode for the extension to start considering current time again in order to switch themes.

Also, the extension seems to conflict with https://github.com/shanalikhan/code-settings-sync extension with enabled settings-download on start.
I start VSCode, nightswitch switches to the theme according to current time, then code-settings-sync downloads the settings from another machine and applies them, disregarding the theme set by nightswitch.

I'm running Linux Mint 18.3 Sylvia, VSCode 1.20.1, NightSwitch 1.06. Let me know if additional info needed.

**Comment by gharveymn** [comment]
Thanks for the thorough report. I'm quite busy with school at the moment, but I'll look into this when I can.

**Comment by gharveymn** [comment]
Fixed by removing timed promises---now just checks whenever the window changes focus.

**Comment by vacore** [comment]
Confirm and happy this is working now. Thanks
